services:
  my-app:
    build:
      context: .
    ports:
      - "3000:3000"
    develop:
     watch:
      - action: sync+restart
        path: .
        target: /app
        ignore:
          - node_modules/
          - .next/